# Generated by Django 3.2.18 on 2023-05-24 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_header', models.CharField(max_length=100)),
                ('sub_header', models.CharField(max_length=100)),
                ('par1', models.CharField(max_length=300)),
                ('par2', models.CharField(max_length=300)),
                ('par3', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('nationality', models.CharField(max_length=200)),
                ('residency', models.CharField(max_length=200)),
                ('languages', models.CharField(max_length=200)),
                ('studying', models.CharField(max_length=200)),
                ('flag_nationality', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('flag_residency', models.ImageField(blank=True, null=True, upload_to='flags/')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('description', models.CharField(max_length=200)),
                ('github_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_heading', models.CharField(max_length=100)),
                ('language_icon1', models.URLField(blank=True, max_length=100, null=True)),
                ('language_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('language_icon2', models.URLField(blank=True, max_length=100, null=True)),
                ('language_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('language_icon3', models.URLField(blank=True, max_length=100, null=True)),
                ('language_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('language_icon4', models.URLField(blank=True, max_length=100, null=True)),
                ('language_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('language_icon5', models.URLField(blank=True, max_length=100, null=True)),
                ('language_name5', models.CharField(blank=True, max_length=100, null=True)),
                ('framework_heading', models.CharField(max_length=100)),
                ('framework_icon1', models.URLField(blank=True, max_length=100, null=True)),
                ('framework_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('framework_icon2', models.URLField(blank=True, max_length=100, null=True)),
                ('framework_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('framework_icon3', models.URLField(blank=True, max_length=100, null=True)),
                ('framework_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('framework_icon4', models.URLField(blank=True, max_length=100, null=True)),
                ('framework_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('framework_icon5', models.URLField(blank=True, max_length=100, null=True)),
                ('framework_name5', models.CharField(blank=True, max_length=100, null=True)),
                ('database_heading', models.CharField(max_length=100)),
                ('database_icon1', models.URLField(blank=True, max_length=100, null=True)),
                ('database_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('database_icon2', models.URLField(blank=True, max_length=100, null=True)),
                ('database_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('database_icon3', models.URLField(blank=True, max_length=100, null=True)),
                ('database_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('database_icon4', models.URLField(blank=True, max_length=100, null=True)),
                ('database_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('database_icon5', models.URLField(blank=True, max_length=100, null=True)),
                ('database_name5', models.CharField(blank=True, max_length=100, null=True)),
                ('version_control_heading', models.CharField(max_length=100)),
                ('version_control_icon1', models.URLField(blank=True, max_length=100, null=True)),
                ('version_control_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('version_control_icon2', models.URLField(blank=True, max_length=100, null=True)),
                ('version_control_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('version_control_icon3', models.URLField(blank=True, max_length=100, null=True)),
                ('version_control_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('version_control_icon4', models.URLField(blank=True, max_length=100, null=True)),
                ('version_control_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('version_control_icon5', models.URLField(blank=True, max_length=100, null=True)),
                ('version_control_name5', models.CharField(blank=True, max_length=100, null=True)),
                ('library_heading', models.CharField(max_length=100)),
                ('library_icon1', models.URLField(blank=True, max_length=100, null=True)),
                ('library_name1', models.CharField(blank=True, max_length=100, null=True)),
                ('library_icon2', models.URLField(blank=True, max_length=100, null=True)),
                ('library_name2', models.CharField(blank=True, max_length=100, null=True)),
                ('library_icon3', models.URLField(blank=True, max_length=100, null=True)),
                ('library_name3', models.CharField(blank=True, max_length=100, null=True)),
                ('library_icon4', models.URLField(blank=True, max_length=100, null=True)),
                ('library_name4', models.CharField(blank=True, max_length=100, null=True)),
                ('library_icon5', models.URLField(blank=True, max_length=100, null=True)),
                ('library_name5', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
