# Generated by Django 3.2.18 on 2023-05-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('big_header', models.CharField(max_length=100)),
                ('sub_header', models.CharField(max_length=100)),
                ('par1', models.CharField(max_length=300)),
            ],
        ),
    ]
