# Generated by Django 3.2.18 on 2023-05-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0002_headings'),
    ]

    operations = [
        migrations.AddField(
            model_name='headings',
            name='par2',
            field=models.CharField(default='qweerty', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='headings',
            name='par3',
            field=models.CharField(default='qwerty', max_length=300),
            preserve_default=False,
        ),
    ]
