# Generated by Django 3.2.18 on 2023-05-07 13:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0003_framework_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='framework',
            name='image',
            field=models.ImageField(upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='language',
            name='image',
            field=models.ImageField(upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
        ),
    ]
