# Generated by Django 3.2.18 on 2023-05-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0003_auto_20230517_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaldetails',
            name='age',
            field=models.PositiveBigIntegerField(default='2'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='flag_nationality',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
        migrations.AddField(
            model_name='personaldetails',
            name='flag_residency',
            field=models.ImageField(blank=True, null=True, upload_to='flags/'),
        ),
    ]
