# Generated by Django 3.2.18 on 2023-05-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0004_auto_20230518_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='project_images/')),
                ('github_url', models.URLField()),
            ],
        ),
    ]
