# Generated by Django 3.2.18 on 2023-05-08 17:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0005_auto_20230507_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='framework',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='framework',
            name='image2',
            field=models.ImageField(default='staticfiles/media/frameworks_images/django.png', upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framework',
            name='image3',
            field=models.ImageField(default='staticfiles/media/frameworks_images/django.png', upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framework',
            name='image4',
            field=models.ImageField(default='staticfiles/media/frameworks_images/django.png', upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='framework',
            name='image5',
            field=models.ImageField(default='staticfiles/media/frameworks_images/django.png', upload_to='skills/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
    ]
