# Generated by Django 3.2.18 on 2023-05-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0006_auto_20230520_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='language_href1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href2',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href3',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href4',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href5',
            field=models.URLField(),
        ),
    ]
