# Generated by Django 3.2.18 on 2023-05-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0007_auto_20230520_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='framework_href1',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework_href2',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework_href3',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework_href4',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework_href5',
            field=models.URLField(),
        ),
    ]
