# Generated by Django 3.2.18 on 2023-05-20 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0008_auto_20230520_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='language_href1',
            field=models.ImageField(upload_to=''),
        ),
    ]
