# Generated by Django 3.2.18 on 2023-05-09 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0009_versioncontrol'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='image4',
            field=models.ImageField(default='media/skills', upload_to='libraries/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='image5',
            field=models.ImageField(default='media/skills', upload_to='libraries/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versioncontrol',
            name='image4',
            field=models.ImageField(default='media/skills', upload_to='version-control/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='versioncontrol',
            name='image5',
            field=models.ImageField(default='media/skills', upload_to='version-control/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])]),
            preserve_default=False,
        ),
    ]
