# Generated by Django 3.2.18 on 2023-05-20 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0009_alter_skills_language_href1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='framework_href1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework_href2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework_href3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework_href4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='framework_href5',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href4',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='language_href5',
            field=models.CharField(max_length=200),
        ),
    ]
