# Generated by Django 3.2.18 on 2023-05-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0010_auto_20230520_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skills',
            name='database_href1',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='database_href2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='database_href3',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='database_href4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='database_href5',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='framework_href1',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='framework_href2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='framework_href3',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='framework_href4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='framework_href5',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='language_href1',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='language_href2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='language_href3',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='language_href4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='language_href5',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='library_href1',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='library_href2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='library_href3',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='library_href4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='library_href5',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='version_control_href1',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='version_control_href2',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='version_control_href3',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='version_control_href4',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='version_control_href5',
        ),
        migrations.AddField(
            model_name='skills',
            name='database_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='language_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='library_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='version_control_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
