# Generated by Django 3.2.18 on 2023-05-20 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0011_auto_20230520_1923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='database_icon',
            new_name='database_icon1',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='framework_icon',
            new_name='database_icon2',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='language_icon',
            new_name='database_icon3',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='library_icon',
            new_name='database_icon4',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='version_control_icon',
            new_name='database_icon5',
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_icon1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_icon2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_icon3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_icon4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='framework_icon5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='language_icon1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='language_icon2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='language_icon3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='language_icon4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='language_icon5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='library_icon1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='library_icon2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='library_icon3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='library_icon4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='library_icon5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='version_control_icon1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='version_control_icon2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='version_control_icon3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='version_control_icon4',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='skills',
            name='version_control_icon5',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
