# Generated by Django 3.2.18 on 2023-05-20 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0012_auto_20230520_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='language_icon1',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
    ]
