# Generated by Django 3.2.18 on 2023-05-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0017_auto_20230521_1108'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skills',
            old_name='database_name',
            new_name='database_heading',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='framework_name',
            new_name='framework_heading',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='language_name',
            new_name='language_heading',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='library_name',
            new_name='library_heading',
        ),
        migrations.RenameField(
            model_name='skills',
            old_name='version_control_name',
            new_name='version_control_heading',
        ),
    ]
