# Generated by Django 3.2.18 on 2023-05-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_pf', '0018_auto_20230521_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description',
            field=models.CharField(default='describe', max_length=200),
            preserve_default=False,
        ),
    ]
